## Autoconf processes this file and replaces the strings in @..@
##    If configured --with-trilinos, this pulls in a Makefile where
##       Trilinos variables are defined (e.g. Trilinos_LIBS), which
##       are used in  src/fortran/Makefile.am within an uf Trilinos block.
##    Else, this just becomes an unused comment

 include /contrib/trilinos/10.6.2/include/Makefile.export.Trilinos
