function res = vel_grad_v(su,sv,dx,dy)

  %%% idea: uv_x + vv_y = div((uv,vv)) - v div(u,v)

  [m,n] = size(su);
  m = m+1;

  %estimate of div(uv,vv)
 div1 =( su(2:end  ,2:end-1,:).*0.25.*(sv(2:end-1,1:end-1,:)+...
				       sv(2:end-1,2:end  ,:)+...
				       sv(3:end  ,1:end-1,:)+...
				       sv(3:end  ,2:end  ,:)) ...
        -su(1:end-1,2:end-1,:).*0.25.*(sv(1:end-2,1:end-1,:)+...
				       sv(1:end-2,2:end  ,:)+...
				       sv(2:end-1,1:end-1,:)+...
				       sv(2:end-1,2:end  ,:)) ) /dx + ...
       ( sv(2:end-1,2:end,:).^2 - sv(2:end-1,1:end-1,:).^2) / dy;  

% estimate of v div(u,v)
  div2 = 0.5*(sv(2:end-1,1:end-1,:)+sv(2:end-1,2:end,:)) .* ...
  ((su(2:end,2:end-1,:) - su(1:end-1,2:end-1,:))/dx + ...
   (sv(2:end-1,2:end,:) - sv(2:end-1,1:end-1,:))/dy);

res = zeros(m,n);
res(2:end-1,2:end-1) = div1-div2;


end

