#!/bin/sh

# edit this with the right compiler and netcdf installation areas
FC=gfortran
NETCDF=/home/cvg222/install/netcdf/
INCFLAG=I
BIN=/home/cvg222/bin/
 
$FC -o nc_regrid -$INCFLAG $NETCDF/include -L $NETCDF/lib ./nc_regrid.F90 -lnetcdf
mv ./nc_regrid $BIN/nc_regrid


