#!/bin/sh

# edit this with the right compiler and netcdf installation areas
FC=gfortran
NETCDF=/home/cvg222/install/netcdf/
INCFLAG=I
BIN=/home/cvg222/bin/
 
$FC -o nc_gen_input -$INCFLAG $NETCDF/include -L $NETCDF/lib ./nc_gen_input.F90 -lnetcdf
mv ./nc_gen_input $BIN/nc_gen_input

